// <auto-generated />
namespace TreinaWeb.ProdutosMarcas.Persistencia.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Migration_Inicial_Criacao_Produto_Marca : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migration_Inicial_Criacao_Produto_Marca));
        
        string IMigrationMetadata.Id
        {
            get { return "201901311258266_Migration_Inicial_Criacao_Produto_Marca"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
